service: pdfshare-serverless

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  profile: default
  region: eu-north-1
  timeout: 20
  environment:
    MONGO_URI: *****

functions:
  getMetadata:
    handler: ./handlers/metadata-handler.getMetadata
    events:
      - http:
          path: files
          method: get
  addMetadata:
    handler: ./handlers/metadata-handler.addMetadata
    events:
      - http:
          path: files/new
          method: post
  getMetadataByUserId:
    handler: ./handlers/metadata-handler.getMetadataByUserId
    events:
      - http:
          path: files/user/{userId}
          method: get
  getMetadataById:
    handler: ./handlers/metadata-handler.getMetadataById
    events:
      - http:
          path: file/{fileId}
          method: get
  deleteMetadata:
    handler: ./handlers/metadata-handler.deleteMetadata
    events: 
      - http:
          path: file/{fileId}
          method: delete
  getUsers:
    handler: ./handlers/user-handler.getUsers
    events:
      - http:
          path: auth/user/all
          method: get
  createUser:
    handler: ./handlers/user-handler.createUser
    events:
      - http:
          path: auth/user
          method: post
  getUserById:
    handler: ./handlers/user-handler.getUserById
    events:
      - http:
          path: auth/user/{userId}
          method: get
  updateUserById:
    handler: ./handlers/user-handler.updateUserById
    events:
      - http:
          path: auth/user/{userId}
          method: put
  deleteUserById:
    handler: ./handlers/user-handler.deleteUserById
    events:
      - http:
          path: auth/user/{userId}
          method: delete
plugins:
  - serverless-offline